# Control-Value Theory priors
# P(Bt | St): likelihood of observing behavior B given state S

EMISSION_PROBS = {
    "flow": {
        "high_ikl": 0.1,
        "high_pel": 0.1,
        "high_backspace": 0.15,
        "high_pause": 0.1,
        "rapid_resubmission": 0.05,
        "schema_hovering": 0.1,
        "low_rar": 0.1,
        "high_tfk": 0.1,
        "high_error_repetition": 0.1,
        "high_rewrites": 0.05,
        "low_pause_burst": 0.05,
        "skimmed_prompt": 0.1,
        "low_paste": 0.3,
        "low_pause_q12": 0.3,
        "productive_pause_q5": 0.85,
    },
    "frustration": {
        "high_ikl": 0.7,
        "high_pel": 0.8,
        "high_backspace": 0.75,
        "high_pause": 0.7,
        "rapid_resubmission": 0.6,
        "schema_hovering": 0.3,
        "low_rar": 0.4,
        "high_tfk": 0.3,
        "high_error_repetition": 0.7,
        "high_rewrites": 0.85,
        "low_pause_burst": 0.05,
        "skimmed_prompt": 0.2,
        "low_paste": 0.3,
        "low_pause_q12": 0.1,
        "productive_pause_q5": 0.1,
    },
    "impulsivity": {
        "high_ikl": 0.1,
        "high_pel": 0.2,
        "high_backspace": 0.3,
        "high_pause": 0.1,
        "rapid_resubmission": 0.9,
        "schema_hovering": 0.1,
        "low_rar": 0.85,
        "high_tfk": 0.05,
        "high_error_repetition": 0.5,
        "high_rewrites": 0.2,
        "low_pause_burst": 0.95,
        "skimmed_prompt": 0.8,
        "low_paste": 0.85,
        "low_pause_q12": 0.85,
        "productive_pause_q5": 0.05,
    },
    "uncertainty": {
        "high_ikl": 0.5,
        "high_pel": 0.7,
        "high_backspace": 0.3,
        "high_pause": 0.8,
        "rapid_resubmission": 0.2,
        "schema_hovering": 0.92,
        "low_rar": 0.2,
        "high_tfk": 0.4,
        "high_error_repetition": 0.4,
        "high_rewrites": 0.2,
        "low_pause_burst": 0.02,
        "skimmed_prompt": 0.1,
        "low_paste": 0.3,
        "low_pause_q12": 0.1,
        "productive_pause_q5": 0.2,
    },
    "anxiety": {
        "high_ikl": 0.6,
        "high_pel": 0.5,
        "high_backspace": 0.2,
        "high_pause": 0.6,
        "rapid_resubmission": 0.2,
        "schema_hovering": 0.3,
        "low_rar": 0.2,
        "high_tfk": 0.9,
        "high_error_repetition": 0.3,
        "high_rewrites": 0.15,
        "low_pause_burst": 0.05,
        "skimmed_prompt": 0.05,
        "low_paste": 0.3,
        "low_pause_q12": 0.1,
        "productive_pause_q5": 0.1,
    },
}

TRANSITION_PROBS = {
    "flow":        {"flow": 0.7, "frustration": 0.1, "impulsivity": 0.1, "uncertainty": 0.05, "anxiety": 0.05},
    "frustration": {"flow": 0.2, "frustration": 0.6, "impulsivity": 0.1, "uncertainty": 0.05, "anxiety": 0.05},
    "impulsivity": {"flow": 0.3, "frustration": 0.1, "impulsivity": 0.5, "uncertainty": 0.05, "anxiety": 0.05},
    "uncertainty": {"flow": 0.2, "frustration": 0.1, "impulsivity": 0.1, "uncertainty": 0.55, "anxiety": 0.05},
    "anxiety":     {"flow": 0.2, "frustration": 0.1, "impulsivity": 0.1, "uncertainty": 0.1,  "anxiety": 0.5},
}

INITIAL_PROBS = {
    "flow": 0.6,
    "frustration": 0.1,
    "impulsivity": 0.1,
    "uncertainty": 0.1,
    "anxiety": 0.1,
}